version: '2.1'

services:
  mongodb:
    image: mongo
    ports:
      - "27018:27018"
    restart: always
    healthcheck:
      test: "exit 0"
    networks:
      - my-network
    volumes:
      - mongodata:/data/db
    
  tradingsmicro:
    build: .
    links:
      - 'mongodb'
    depends_on: 
      mongodb:
        condition: service_healthy
    environment:
      - WAIT_HOSTS=mongodb:27018
    entrypoint:
      - /usr/local/bin/docker-entrypoint.sh
    ports:
      - "4005:4005"
    networks:
      - my-network
    
networks:
  my-network:
    name: net

volumes:
  mongodata: